remote_theme: pages-themes/midnight@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Site Metadata
title: "Thomas Dall to Tim Dooley Archive"
description: "Public documentation of the Transition of Thomas Dall into Tim Dooley, The Potato of Life"
