name: Daily Sync
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yt-dlp
        run: sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && sudo chmod a+rx /usr/local/bin/yt-dlp
      - name: Run Sync
        run: |
         cd archive
         python update_archive.py
      - name: Save Changes
        run: |
          git config user.name "Archive Bot"
          git config user.email "bot@github.com"
          git add archive/archive.json
          git commit -m "Updated archive" || exit 0
          git push
